export const ChannelNames = {
  loginSuccess: 'LoginSuccess',
  closeWindow: 'closeWindow',
  switchWindowsSize: 'switchWindowSize',
  hideWindow: 'hideWindow',
  initWindow: 'initWindow',
  openNewWindow: 'openNewWindow',
  openNewWindowWithPath: 'openNewWindowWithPath',
  getWindowIntent: 'getWindowIntent',
  getRemoteInfo: 'getRemoteInfo',
  setClipboard: 'setClipboard',
  clipboardUpdated: 'clipboardUpdated',
  getClipboard: 'getClipboard',
  getTasks: 'getTasks',
  getFileDir: 'getFileDir',
  directoryUpdate: 'directoryUpdate',
  directoryUpdated: 'directoryUpdated',
  favouriteUpdate: 'favouriteUpdate',
  favouriteUpdated: 'favouriteUpdated',
  notificationCopyTaskComplete: 'NotificationCopyTaskComplete',
  notificationDeleteTaskComplete: 'NotificationDeleteTaskComplete',
  notificationExtractTaskComplete: 'UnarchiveTaskComplete',
  notificationMoveTaskComplete: 'NotificationMoveTaskComplete'
}
